services:
  redis:
    image: redis:7-alpine
    container_name: kb-redis
    restart: always
    volumes:
      - kb-redis-data:/data
    networks:
      - kawanbelanja-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
    command: redis-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru

volumes:
  kb-redis-data:
    name: kb-redis-data

networks:
  kawanbelanja-net:
    external: true
